Theodo\RogerCmsBundle\Entity\Layout:
    type: entity
    table: layout
    gedmo:
      locale: ~

    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 255
            unique: true
        content:
            type: text
            gedmo:
              - translatable

        created_at:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updated_at:
            type: datetime
            gedmo:
                timestampable:
                    on: update