# Admin routing
login:
    pattern:  /admin/{_locale}
    defaults: { _controller: TheodoRogerCmsBundle:Backend\User:login }
    requirements:
        _locale: en|fr|de

login_check:
    pattern:   /admin/int/login

logout:
    pattern:   /admin/int/logout

user_accessDenied:
    pattern: /admin/{_locale}/access-denied
    defaults: { _controller: TheodoRogerCmsBundle:Backend\User:accessDenied, _locale: fr }
    requirements:
        _locale: en|fr|de

# User routing
user_list:
    pattern:  /admin/{_locale}/users
    defaults: { _controller: TheodoRogerCmsBundle:Backend\User:list, tab: settings, nav: users }

user_edit:
    pattern:  /admin/{_locale}/users/{id}/edit
    defaults: { _controller: TheodoRogerCmsBundle:Backend\User:edit, self: false, tab: settings, nav: users }

user_new:
    pattern:  /admin/{_locale}/users/new
    defaults: { _controller: TheodoRogerCmsBundle:Backend\User:edit, id: null, self: false, tab: settings, nav: users }

user_remove:
    pattern:  /admin/{_locale}/users/{id}/remove
    defaults: { _controller: TheodoRogerCmsBundle:Backend\User:remove, tab: settings, nav: users }

user_preferences:
    pattern:  /admin/{_locale}/preferences/edit
    defaults: { _controller: TheodoRogerCmsBundle:Backend\User:edit, id: null, self: true, tab: settings, nav: personal }

user_preferencesUpdate:
    pattern:  /admin/{_locale}/preferences/update
    defaults: { _controller: TheodoRogerCmsBundle:Backend\User:edit, id: null, self: true, tab: settings, nav: personal }

user_update:
    pattern:  /admin/{_locale}/users/{id}/update
    defaults: { _controller: TheodoRogerCmsBundle:Backend\User:edit, self: false, tab: settings, nav: personal }

user_checkSessionLocale:
    pattern:  /admin/{_locale}/check-session/{redirect_route}
    defaults: { _controller: TheodoRogerCmsBundle:Backend\User:checkSessionLocale }

# Page routing
page_list:
    pattern:  /admin/{_locale}/pages
    defaults: { _controller: TheodoRogerCmsBundle:Backend\Page:index, tab: content, nav: pages, _locale: fr }
    requirements:
        _locale: en|fr|de|nl
page_new:
    pattern:  /admin/{_locale}/pages/{parent_id}/new
    defaults: { _controller: TheodoRogerCmsBundle:Backend\Page:edit, id: null, tab: content, nav: pages }

page_edit:
    pattern:  /admin/{_locale}/pages/{id}/edit
    defaults: { _controller: TheodoRogerCmsBundle:Backend\Page:edit, tab: content, nav: pages }

page_update:
    pattern:  /admin/{_locale}/pages/{id}/update
    defaults: { _controller: TheodoRogerCmsBundle:Backend\Page:edit, tab: content, nav: pages }

page_remove:
    pattern:  /admin/{_locale}/pages/{id}/remove
    defaults: { _controller: TheodoRogerCmsBundle:Backend\Page:remove, tab: content, nav: pages }

page_expand:
    pattern:  /admin/{_locale}/pages/{id}/expand/{level}
    defaults: { _controller: TheodoRogerCmsBundle:Backend\Page:expand, tab: content, nav: pages }

# Layout routing
layout_new:
    pattern: /admin/{_locale}/layouts/new
    defaults: { _controller: TheodoRogerCmsBundle:Backend\Layout:edit, id: null, tab: design, nav: layouts }

layout_update:
    pattern: /admin/{_locale}/layouts/{id}
    defaults: { _controller: TheodoRogerCmsBundle:Backend\Layout:edit, tab: design, nav: layouts }

layout_edit:
    pattern: /admin/{_locale}/layouts/{id}/edit
    defaults: { _controller: TheodoRogerCmsBundle:Backend\Layout:edit, tab: design, nav: layouts }

layout_list:
    pattern: /admin/{_locale}/layouts
    defaults: { _controller: TheodoRogerCmsBundle:Backend\Layout:index, tab: design, nav: layouts }

layout_remove:
    pattern: /admin/{_locale}/layouts/{id}/remove
    defaults: { _controller: TheodoRogerCmsBundle:Backend\Layout:remove, tab: design, nav: layouts }

# Snippet routing
snippet_new:
    pattern: /admin/{_locale}/snippets/new
    defaults: { _controller: TheodoRogerCmsBundle:Backend\Snippet:edit, id: null, tab: design, nav: snippets }

snippet_update:
    pattern: /admin/{_locale}/snippets/{id}
    defaults: { _controller: TheodoRogerCmsBundle:Backend\Snippet:edit, tab: design, nav: snippets }

snippet_edit:
    pattern: /admin/{_locale}/snippets/{id}/edit
    defaults: { _controller: TheodoRogerCmsBundle:Backend\Snippet:edit, tab: design, nav: snippets }

snippet_list:
    pattern: /admin/{_locale}/snippets
    defaults: { _controller: TheodoRogerCmsBundle:Backend\Snippet:index, tab: design, nav: snippets }

snippet_remove:
    pattern: /admin/{_locale}/snippets/{id}/remove
    defaults: { _controller: TheodoRogerCmsBundle:Backend\Snippet:remove, tab: design, nav: snippets }

# Media routing
media_new:
    pattern: /admin/{_locale}/medias/new
    defaults: { _controller: TheodoRogerCmsBundle:Backend\Media:edit, id: null, tab: content, nav: medias }

media_update:
    pattern: /admin/{_locale}/medias/{id}
    defaults: { _controller: TheodoRogerCmsBundle:Backend\Media:edit, tab: content, nav: medias }

media_edit:
    pattern: /admin/{_locale}/medias/{id}/edit
    defaults: { _controller: TheodoRogerCmsBundle:Backend\Media:edit, tab: content, nav: medias }

media_list:
    pattern: /admin/{_locale}/medias
    defaults: { _controller: TheodoRogerCmsBundle:Backend\Media:index, tab: content, nav: medias }

media_remove:
    pattern: /admin/{_locale}/medias/{id}/remove
    defaults: { _controller: TheodoRogerCmsBundle:Backend\Media:remove, tab: content, nav: medias }

# ESI routing
_internal:
    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
    prefix:   /_internal

# Frontend routing
page:
    pattern: /{slug}
    defaults: { _controller: TheodoRogerCmsBundle:Frontend\Frontend:page, slug: 'homepage'}
    requirements:
        slug: ".+"